// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: shared.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tibia.Protobuf.Shared {

  /// <summary>Holder for reflection information generated from shared.proto</summary>
  public static partial class SharedReflection {

    #region Descriptor
    /// <summary>File descriptor for shared.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SharedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxzaGFyZWQucHJvdG8SFXRpYmlhLnByb3RvYnVmLnNoYXJlZCqUAQoNUExB",
            "WUVSX0FDVElPThIWChJQTEFZRVJfQUNUSU9OX05PTkUQABIWChJQTEFZRVJf",
            "QUNUSU9OX0xPT0sQARIVChFQTEFZRVJfQUNUSU9OX1VTRRACEhYKElBMQVlF",
            "Ul9BQ1RJT05fT1BFThADEiQKIFBMQVlFUl9BQ1RJT05fQVVUT1dBTEtfSElH",
            "SExJR0hUEAQqpgUKDUlURU1fQ0FURUdPUlkSFgoSSVRFTV9DQVRFR09SWV9O",
            "T05FEAASGAoUSVRFTV9DQVRFR09SWV9BUk1PUlMQARIZChVJVEVNX0NBVEVH",
            "T1JZX0FNVUxFVFMQAhIXChNJVEVNX0NBVEVHT1JZX0JPT1RTEAMSHAoYSVRF",
            "TV9DQVRFR09SWV9DT05UQUlORVJTEAQSHAoYSVRFTV9DQVRFR09SWV9ERUNP",
            "UkFUSU9OEAUSFgoSSVRFTV9DQVRFR09SWV9GT09EEAYSHgoaSVRFTV9DQVRF",
            "R09SWV9IRUxNRVRTX0hBVFMQBxIWChJJVEVNX0NBVEVHT1JZX0xFR1MQCBIY",
            "ChRJVEVNX0NBVEVHT1JZX09USEVSUxAJEhkKFUlURU1fQ0FURUdPUllfUE9U",
            "SU9OUxAKEhcKE0lURU1fQ0FURUdPUllfUklOR1MQCxIXChNJVEVNX0NBVEVH",
            "T1JZX1JVTkVTEAwSGQoVSVRFTV9DQVRFR09SWV9TSElFTERTEA0SFwoTSVRF",
            "TV9DQVRFR09SWV9UT09MUxAOEhsKF0lURU1fQ0FURUdPUllfVkFMVUFCTEVT",
            "EA8SHAoYSVRFTV9DQVRFR09SWV9BTU1VTklUSU9OEBASFgoSSVRFTV9DQVRF",
            "R09SWV9BWEVTEBESFwoTSVRFTV9DQVRFR09SWV9DTFVCUxASEiIKHklURU1f",
            "Q0FURUdPUllfRElTVEFOQ0VfV0VBUE9OUxATEhgKFElURU1fQ0FURUdPUllf",
            "U1dPUkRTEBQSHAoYSVRFTV9DQVRFR09SWV9XQU5EU19ST0RTEBUSIQodSVRF",
            "TV9DQVRFR09SWV9QUkVNSVVNX1NDUk9MTFMQFhIdChlJVEVNX0NBVEVHT1JZ",
            "X1RJQklBX0NPSU5TEBcq7QEKEVBMQVlFUl9QUk9GRVNTSU9OEhoKFlBMQVlF",
            "Ul9QUk9GRVNTSU9OX05PTkUQABIcChhQTEFZRVJfUFJPRkVTU0lPTl9LTklH",
            "SFQQARIdChlQTEFZRVJfUFJPRkVTU0lPTl9QQUxBRElOEAISHgoaUExBWUVS",
            "X1BST0ZFU1NJT05fU09SQ0VSRVIQAxIbChdQTEFZRVJfUFJPRkVTU0lPTl9E",
            "UlVJRBAEEh4KGlBMQVlFUl9QUk9GRVNTSU9OX1BST01PVEVEEAoSIgoVUExB",
            "WUVSX1BST0ZFU1NJT05fQU5ZEP///////////wEqgwEKE0FOSU1BVElPTl9M",
            "T09QX1RZUEUSIAocQU5JTUFUSU9OX0xPT1BfVFlQRV9JTkZJTklURRAAEh8K",
            "G0FOSU1BVElPTl9MT09QX1RZUEVfQ09VTlRFRBABEikKHEFOSU1BVElPTl9M",
            "T09QX1RZUEVfUElOR1BPTkcQ////////////ASpICglIT09LX1RZUEUSEgoO",
            "SE9PS19UWVBFX05PTkUQABITCg9IT09LX1RZUEVfU09VVEgQARISCg5IT09L",
            "X1RZUEVfRUFTVBACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tibia.Protobuf.Shared.PLAYER_ACTION), typeof(global::Tibia.Protobuf.Shared.ITEM_CATEGORY), typeof(global::Tibia.Protobuf.Shared.PLAYER_PROFESSION), typeof(global::Tibia.Protobuf.Shared.ANIMATION_LOOP_TYPE), typeof(global::Tibia.Protobuf.Shared.HOOK_TYPE), }, null));
    }
    #endregion

  }
  #region Enums
  public enum PLAYER_ACTION {
    [pbr::OriginalName("PLAYER_ACTION_NONE")] None = 0,
    [pbr::OriginalName("PLAYER_ACTION_LOOK")] Look = 1,
    [pbr::OriginalName("PLAYER_ACTION_USE")] Use = 2,
    [pbr::OriginalName("PLAYER_ACTION_OPEN")] Open = 3,
    [pbr::OriginalName("PLAYER_ACTION_AUTOWALK_HIGHLIGHT")] AutowalkHighlight = 4,
  }

  public enum ITEM_CATEGORY {
    [pbr::OriginalName("ITEM_CATEGORY_NONE")] None = 0,
    [pbr::OriginalName("ITEM_CATEGORY_ARMORS")] Armors = 1,
    [pbr::OriginalName("ITEM_CATEGORY_AMULETS")] Amulets = 2,
    [pbr::OriginalName("ITEM_CATEGORY_BOOTS")] Boots = 3,
    [pbr::OriginalName("ITEM_CATEGORY_CONTAINERS")] Containers = 4,
    [pbr::OriginalName("ITEM_CATEGORY_DECORATION")] Decoration = 5,
    [pbr::OriginalName("ITEM_CATEGORY_FOOD")] Food = 6,
    [pbr::OriginalName("ITEM_CATEGORY_HELMETS_HATS")] HelmetsHats = 7,
    [pbr::OriginalName("ITEM_CATEGORY_LEGS")] Legs = 8,
    [pbr::OriginalName("ITEM_CATEGORY_OTHERS")] Others = 9,
    [pbr::OriginalName("ITEM_CATEGORY_POTIONS")] Potions = 10,
    [pbr::OriginalName("ITEM_CATEGORY_RINGS")] Rings = 11,
    [pbr::OriginalName("ITEM_CATEGORY_RUNES")] Runes = 12,
    [pbr::OriginalName("ITEM_CATEGORY_SHIELDS")] Shields = 13,
    [pbr::OriginalName("ITEM_CATEGORY_TOOLS")] Tools = 14,
    [pbr::OriginalName("ITEM_CATEGORY_VALUABLES")] Valuables = 15,
    [pbr::OriginalName("ITEM_CATEGORY_AMMUNITION")] Ammunition = 16,
    [pbr::OriginalName("ITEM_CATEGORY_AXES")] Axes = 17,
    [pbr::OriginalName("ITEM_CATEGORY_CLUBS")] Clubs = 18,
    [pbr::OriginalName("ITEM_CATEGORY_DISTANCE_WEAPONS")] DistanceWeapons = 19,
    [pbr::OriginalName("ITEM_CATEGORY_SWORDS")] Swords = 20,
    [pbr::OriginalName("ITEM_CATEGORY_WANDS_RODS")] WandsRods = 21,
    [pbr::OriginalName("ITEM_CATEGORY_PREMIUM_SCROLLS")] PremiumScrolls = 22,
    [pbr::OriginalName("ITEM_CATEGORY_TIBIA_COINS")] TibiaCoins = 23,
  }

  public enum PLAYER_PROFESSION {
    [pbr::OriginalName("PLAYER_PROFESSION_NONE")] None = 0,
    [pbr::OriginalName("PLAYER_PROFESSION_KNIGHT")] Knight = 1,
    [pbr::OriginalName("PLAYER_PROFESSION_PALADIN")] Paladin = 2,
    [pbr::OriginalName("PLAYER_PROFESSION_SORCERER")] Sorcerer = 3,
    [pbr::OriginalName("PLAYER_PROFESSION_DRUID")] Druid = 4,
    [pbr::OriginalName("PLAYER_PROFESSION_PROMOTED")] Promoted = 10,
    [pbr::OriginalName("PLAYER_PROFESSION_ANY")] Any = -1,
  }

  public enum ANIMATION_LOOP_TYPE {
    [pbr::OriginalName("ANIMATION_LOOP_TYPE_INFINITE")] Infinite = 0,
    [pbr::OriginalName("ANIMATION_LOOP_TYPE_COUNTED")] Counted = 1,
    [pbr::OriginalName("ANIMATION_LOOP_TYPE_PINGPONG")] Pingpong = -1,
  }

  public enum HOOK_TYPE {
    [pbr::OriginalName("HOOK_TYPE_NONE")] None = 0,
    [pbr::OriginalName("HOOK_TYPE_SOUTH")] South = 1,
    [pbr::OriginalName("HOOK_TYPE_EAST")] East = 2,
  }

  #endregion

}

#endregion Designer generated code
